version: '3.9'

services:
  gateway:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - PORT=3000
      - CORS_ORIGIN=*
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - gateway


