version: '3.9'
services:
  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: "${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-changeme}"
      NEO4J_dbms_security_auth__enabled: "true"
      NEO4J_server_bolt_advertised__address: "neo4j:7687"
      NEO4J_server_http_advertised__address: "neo4j:7474"
      NEO4J_server_default__listen__address: "0.0.0.0"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  crm-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: "3010"
      NODE_ENV: production
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "${NEO4J_USER}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
    ports:
      - "3010:3010"
    depends_on:
      - neo4j

  dashboard-api:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: "3007"
      NODE_ENV: production
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "${NEO4J_USER}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
    ports:
      - "3007:3007"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs:


